apiVersion: automation.cloudbees.io/v1alpha1
name: Validar Integración Codeship y GitHub

on:
  push:
    paths:
      - '**/*'

jobs:
  validar_integracion:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener Archivos Modificados
        run: |
          changes=$(git diff --name-only HEAD^..HEAD)

      - name: Crear Build en Codeship
        uses: codeship/codeship-action@v1
        with:
          build_name: "Validación de Integración"
          build_message: "Verifica que la integración de Codeship y GitHub funciona correctamente"
          build_config_path: ".codeship/config.yml"

      - name: Verificar Build en Codeship
        run: |
          build_status=$(curl -s -X GET https://api.codeship.com/v1/builds/latest | jq -r .status)
          if [[ $build_status == "success" ]]; then
            echo "La integración de Codeship y GitHub funciona correctamente"
          else
            echo "La integración de Codeship y GitHub NO funciona correctamente"
          fi
