apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Labeler

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"