name: Notificar Cambio en Archivo

on:
  push:
    paths:
      - '**/*'

jobs:
  notificar_cambio:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener Archivos Modificados
        run: |
          changes=$(git diff --name-only HEAD^..HEAD)

      - name: Comentar en el Issue
        uses: actions/github-issue-comment@v3
        with:
          issue_number: ${{ github.event.issue.number }}
          body: |
            Se han realizado cambios en los archivos:
            
            ${changes}
