apiVersion: "automation.cloudbees.io/v1alpha1"
name: Notificar Cambio en Archivo

on:
  push:
    paths:
      - '**/*'

jobs:
  notificar_cambio:
    runs-on: ubuntu-latest

    steps:
    - name: Ejecutar Script
      run: |
        changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Se han realizado cambios en los archivos: $changes"
        message="Se han realizado cambios en el repositorio. Archivos modificados: $changes"
        gh issue comment ${{ github.event.issue.number }} --body "$message"
