name: Notificar Cambio en Archivo

on:
  push:
    paths:
      - '**/*'

jobs:
  notificar_cambio:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Python y Node.js
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        node-version: '14'

    - name: Ejecutar Script
      run: |
        const changes = github.context.payload.head_commit.modified.join(', ');
        echo "Se han realizado cambios en los archivos: $changes";
        message="Se han realizado cambios en el repositorio. Archivos modificados: $changes";
        gh issue comment ${{ github.event.issue.number }} --body "$message"
